plugins {
    id "com.android.application"
}

android {
    namespace "com.androidtoolsuite.provider.shizuku"
    compileSdk 35

    defaultConfig {
        applicationId "com.androidtoolsuite.provider.shizuku"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly project(":plugin-sdk")
}
