// Generated by tools/runtime-v2/ats.py generate. Do not edit manually.
export const CONTRACT_VERSION = "2.0.0" as const;
export const PACKAGE_FORMAT_VERSION = 3 as const;
export const RPC_PROTOCOL = "2.0" as const;

export type CapabilityId = "app" | "storage" | "scheduler" | "network.request" | "file.import" | "clipboard" | "notification" | "accessibility.manage" | "shizuku.control";
export type AtsMethod = "accessibility.getConnection" | "accessibility.listServices" | "accessibility.setEnabled" | "app.close" | "app.getSession" | "app.openExternal" | "clipboard.read" | "clipboard.write" | "file.import.pick" | "network.request" | "notification.cancel" | "notification.post" | "scheduler.cancel" | "scheduler.lastRun" | "scheduler.register" | "scheduler.runNow" | "shizuku.connect" | "shizuku.getConnection" | "shizuku.requestPermission" | "storage.blob.close" | "storage.blob.delete" | "storage.blob.openRead" | "storage.blob.openWrite" | "storage.blob.read" | "storage.blob.write" | "storage.dataset.abort" | "storage.dataset.commit" | "storage.dataset.delete" | "storage.dataset.openRead" | "storage.dataset.openWrite" | "storage.dataset.read" | "storage.dataset.write" | "storage.kv.delete" | "storage.kv.get" | "storage.kv.set" | "storage.secret.delete" | "storage.secret.get" | "storage.secret.set";
export type AtsEvent = "accessibility.connectionChanged" | "accessibility.servicesChanged" | "app.containerChanged" | "app.permissionsChanged" | "app.themeChanged" | "app.visibilityChanged" | "scheduler.runChanged" | "shizuku.connectionChanged";
export type AtsErrorCode = "INVALID_REQUEST" | "PROTOCOL_MISMATCH" | "CAPABILITY_UNDECLARED" | "CAPABILITY_UNAVAILABLE" | "CAPABILITY_VERSION_MISMATCH" | "PERMISSION_DENIED" | "CONSENT_REQUIRED" | "PROVIDER_OFFLINE" | "TIMEOUT" | "CANCELLED" | "CANCEL_PENDING" | "RESOURCE_LIMIT" | "NOT_SUPPORTED" | "INTERNAL";
export type CapabilityPermissionMode = "implicit" | "user";
export type CapabilityPermissionRisk = "normal" | "sensitive" | "restricted";
export const METHOD_CAPABILITY = {
  "app.close": "app",
  "app.getSession": "app",
  "app.openExternal": "app",
  "storage.blob.close": "storage",
  "storage.blob.delete": "storage",
  "storage.blob.openRead": "storage",
  "storage.blob.openWrite": "storage",
  "storage.blob.read": "storage",
  "storage.blob.write": "storage",
  "storage.dataset.abort": "storage",
  "storage.dataset.commit": "storage",
  "storage.dataset.delete": "storage",
  "storage.dataset.openRead": "storage",
  "storage.dataset.openWrite": "storage",
  "storage.dataset.read": "storage",
  "storage.dataset.write": "storage",
  "storage.kv.delete": "storage",
  "storage.kv.get": "storage",
  "storage.kv.set": "storage",
  "storage.secret.delete": "storage",
  "storage.secret.get": "storage",
  "storage.secret.set": "storage",
  "scheduler.cancel": "scheduler",
  "scheduler.lastRun": "scheduler",
  "scheduler.register": "scheduler",
  "scheduler.runNow": "scheduler",
  "network.request": "network.request",
  "file.import.pick": "file.import",
  "clipboard.read": "clipboard",
  "clipboard.write": "clipboard",
  "notification.cancel": "notification",
  "notification.post": "notification",
  "accessibility.getConnection": "accessibility.manage",
  "accessibility.listServices": "accessibility.manage",
  "accessibility.setEnabled": "accessibility.manage",
  "shizuku.connect": "shizuku.control",
  "shizuku.getConnection": "shizuku.control",
  "shizuku.requestPermission": "shizuku.control"
} as const satisfies Record<AtsMethod, CapabilityId>;
export const CAPABILITY_PERMISSIONS = {
  "app": {"mode":"implicit","risk":"normal","title":"应用交互","description":"读取当前会话和主题，并响应你在工具中的导航操作。"},
  "storage": {"mode":"implicit","risk":"normal","title":"插件数据","description":"只读写此插件自己的设置、文件、凭据和数据集。"},
  "scheduler": {"mode":"user","risk":"sensitive","title":"后台运行","description":"允许插件按清单中的条件在后台执行任务。"},
  "network.request": {"mode":"user","risk":"sensitive","title":"网络访问","description":"访问插件声明的 HTTPS 域名和请求方式。"},
  "file.import": {"mode":"user","risk":"sensitive","title":"读取所选文件","description":"在你主动选择后读取符合类型和大小限制的文件。"},
  "clipboard": {"mode":"user","risk":"sensitive","title":"剪贴板","description":"在你操作工具时读取或写入剪贴板内容。"},
  "notification": {"mode":"user","risk":"sensitive","title":"发送通知","description":"使用插件声明的通知类别显示或取消通知。"},
  "accessibility.manage": {"mode":"user","risk":"restricted","title":"管理无障碍服务","description":"查看并修改设备上已安装无障碍服务的启用状态。"},
  "shizuku.control": {"mode":"user","risk":"restricted","title":"管理 Shizuku 连接","description":"请求本应用的 Shizuku 授权并连接受控系统服务。"}
} as const satisfies Record<CapabilityId, {
  mode: CapabilityPermissionMode;
  risk: CapabilityPermissionRisk;
  title: string;
  description: string;
}>;
