// Generated by tools/plugin/ats.py generate. Do not edit manually.
package com.androidtoolsuite.runtime.contract;

public final class GeneratedContract {
    public static final String CONTRACT_VERSION = "2.1.0";
    public static final int PACKAGE_FORMAT_VERSION = 3;
    public static final String RPC_PROTOCOL = "2.0";

    private GeneratedContract() {
    }

    public static final class Capabilities {
        public static final String APP = "app";
        public static final String STORAGE = "storage";
        public static final String SCHEDULER = "scheduler";
        public static final String NETWORK_REQUEST = "network.request";
        public static final String FILE_IMPORT = "file.import";
        public static final String FILE_EXPORT = "file.export";
        public static final String SYSTEM_LOGS = "system.logs";
        public static final String CLIPBOARD = "clipboard";
        public static final String NOTIFICATION = "notification";
        public static final String ACCESSIBILITY_MANAGE = "accessibility.manage";
        public static final String SHIZUKU_CONTROL = "shizuku.control";

        private Capabilities() {
        }
    }

    public static final class Methods {
        public static final String ACCESSIBILITY_GETCONNECTION = "accessibility.getConnection";
        public static final String ACCESSIBILITY_LISTSERVICES = "accessibility.listServices";
        public static final String ACCESSIBILITY_SETENABLED = "accessibility.setEnabled";
        public static final String APP_CLOSE = "app.close";
        public static final String APP_GETSESSION = "app.getSession";
        public static final String APP_OPENEXTERNAL = "app.openExternal";
        public static final String CLIPBOARD_READ = "clipboard.read";
        public static final String CLIPBOARD_WRITE = "clipboard.write";
        public static final String FILE_EXPORT_SAVE = "file.export.save";
        public static final String FILE_IMPORT_PICK = "file.import.pick";
        public static final String NETWORK_REQUEST = "network.request";
        public static final String NOTIFICATION_CANCEL = "notification.cancel";
        public static final String NOTIFICATION_POST = "notification.post";
        public static final String SCHEDULER_CANCEL = "scheduler.cancel";
        public static final String SCHEDULER_LASTRUN = "scheduler.lastRun";
        public static final String SCHEDULER_REGISTER = "scheduler.register";
        public static final String SCHEDULER_RUNNOW = "scheduler.runNow";
        public static final String SHIZUKU_CONNECT = "shizuku.connect";
        public static final String SHIZUKU_GETCONNECTION = "shizuku.getConnection";
        public static final String SHIZUKU_REQUESTPERMISSION = "shizuku.requestPermission";
        public static final String STORAGE_BLOB_CLOSE = "storage.blob.close";
        public static final String STORAGE_BLOB_DELETE = "storage.blob.delete";
        public static final String STORAGE_BLOB_OPENREAD = "storage.blob.openRead";
        public static final String STORAGE_BLOB_OPENWRITE = "storage.blob.openWrite";
        public static final String STORAGE_BLOB_READ = "storage.blob.read";
        public static final String STORAGE_BLOB_WRITE = "storage.blob.write";
        public static final String STORAGE_DATASET_ABORT = "storage.dataset.abort";
        public static final String STORAGE_DATASET_COMMIT = "storage.dataset.commit";
        public static final String STORAGE_DATASET_DELETE = "storage.dataset.delete";
        public static final String STORAGE_DATASET_OPENREAD = "storage.dataset.openRead";
        public static final String STORAGE_DATASET_OPENWRITE = "storage.dataset.openWrite";
        public static final String STORAGE_DATASET_READ = "storage.dataset.read";
        public static final String STORAGE_DATASET_WRITE = "storage.dataset.write";
        public static final String STORAGE_KV_DELETE = "storage.kv.delete";
        public static final String STORAGE_KV_GET = "storage.kv.get";
        public static final String STORAGE_KV_SET = "storage.kv.set";
        public static final String STORAGE_SECRET_DELETE = "storage.secret.delete";
        public static final String STORAGE_SECRET_GET = "storage.secret.get";
        public static final String STORAGE_SECRET_SET = "storage.secret.set";
        public static final String SYSTEM_LOGS_SEARCH = "system.logs.search";

        private Methods() {
        }
    }

    public static final class Events {
        public static final String ACCESSIBILITY_CONNECTIONCHANGED = "accessibility.connectionChanged";
        public static final String ACCESSIBILITY_SERVICESCHANGED = "accessibility.servicesChanged";
        public static final String APP_CONTAINERCHANGED = "app.containerChanged";
        public static final String APP_PERMISSIONSCHANGED = "app.permissionsChanged";
        public static final String APP_THEMECHANGED = "app.themeChanged";
        public static final String APP_VISIBILITYCHANGED = "app.visibilityChanged";
        public static final String SCHEDULER_RUNCHANGED = "scheduler.runChanged";
        public static final String SHIZUKU_CONNECTIONCHANGED = "shizuku.connectionChanged";

        private Events() {
        }
    }

    public static String capabilityForMethod(String method) {
        if (method == null) return null;
        switch (method) {
            case "app.close": return "app";
            case "app.getSession": return "app";
            case "app.openExternal": return "app";
            case "storage.blob.close": return "storage";
            case "storage.blob.delete": return "storage";
            case "storage.blob.openRead": return "storage";
            case "storage.blob.openWrite": return "storage";
            case "storage.blob.read": return "storage";
            case "storage.blob.write": return "storage";
            case "storage.dataset.abort": return "storage";
            case "storage.dataset.commit": return "storage";
            case "storage.dataset.delete": return "storage";
            case "storage.dataset.openRead": return "storage";
            case "storage.dataset.openWrite": return "storage";
            case "storage.dataset.read": return "storage";
            case "storage.dataset.write": return "storage";
            case "storage.kv.delete": return "storage";
            case "storage.kv.get": return "storage";
            case "storage.kv.set": return "storage";
            case "storage.secret.delete": return "storage";
            case "storage.secret.get": return "storage";
            case "storage.secret.set": return "storage";
            case "scheduler.cancel": return "scheduler";
            case "scheduler.lastRun": return "scheduler";
            case "scheduler.register": return "scheduler";
            case "scheduler.runNow": return "scheduler";
            case "network.request": return "network.request";
            case "file.import.pick": return "file.import";
            case "file.export.save": return "file.export";
            case "system.logs.search": return "system.logs";
            case "clipboard.read": return "clipboard";
            case "clipboard.write": return "clipboard";
            case "notification.cancel": return "notification";
            case "notification.post": return "notification";
            case "accessibility.getConnection": return "accessibility.manage";
            case "accessibility.listServices": return "accessibility.manage";
            case "accessibility.setEnabled": return "accessibility.manage";
            case "shizuku.connect": return "shizuku.control";
            case "shizuku.getConnection": return "shizuku.control";
            case "shizuku.requestPermission": return "shizuku.control";
            default: return null;
        }
    }

    public static String capabilityForEvent(String event) {
        if (event == null) return null;
        switch (event) {
            case "app.containerChanged": return "app";
            case "app.permissionsChanged": return "app";
            case "app.themeChanged": return "app";
            case "app.visibilityChanged": return "app";
            case "scheduler.runChanged": return "scheduler";
            case "accessibility.connectionChanged": return "accessibility.manage";
            case "accessibility.servicesChanged": return "accessibility.manage";
            case "shizuku.connectionChanged": return "shizuku.control";
            default: return null;
        }
    }

    public static String permissionMode(String capabilityId) {
        if (capabilityId == null) return "user";
        switch (capabilityId) {
            case "app": return "implicit";
            case "storage": return "implicit";
            case "scheduler": return "user";
            case "network.request": return "user";
            case "file.import": return "user";
            case "file.export": return "user";
            case "system.logs": return "user";
            case "clipboard": return "user";
            case "notification": return "user";
            case "accessibility.manage": return "user";
            case "shizuku.control": return "user";
            default: return "user";
        }
    }

    public static String permissionRisk(String capabilityId) {
        if (capabilityId == null) return "restricted";
        switch (capabilityId) {
            case "app": return "normal";
            case "storage": return "normal";
            case "scheduler": return "sensitive";
            case "network.request": return "sensitive";
            case "file.import": return "sensitive";
            case "file.export": return "sensitive";
            case "system.logs": return "restricted";
            case "clipboard": return "sensitive";
            case "notification": return "sensitive";
            case "accessibility.manage": return "restricted";
            case "shizuku.control": return "restricted";
            default: return "restricted";
        }
    }

    public static String permissionTitle(String capabilityId) {
        if (capabilityId == null) return "未知能力";
        switch (capabilityId) {
            case "app": return "应用交互";
            case "storage": return "插件数据";
            case "scheduler": return "后台运行";
            case "network.request": return "网络访问";
            case "file.import": return "读取所选文件";
            case "file.export": return "保存文件";
            case "system.logs": return "读取近期系统日志";
            case "clipboard": return "剪贴板";
            case "notification": return "发送通知";
            case "accessibility.manage": return "管理无障碍服务";
            case "shizuku.control": return "管理 Shizuku 连接";
            default: return capabilityId;
        }
    }

    public static String permissionDescription(String capabilityId) {
        if (capabilityId == null) return "";
        switch (capabilityId) {
            case "app": return "读取当前会话和主题，并响应你在工具中的导航操作。";
            case "storage": return "只读写此插件自己的设置、文件、凭据和数据集。";
            case "scheduler": return "允许插件按清单中的条件在后台执行任务。";
            case "network.request": return "访问插件声明的 HTTPS 域名和请求方式。";
            case "file.import": return "在你主动选择后读取符合类型和大小限制的文件。";
            case "file.export": return "在你主动操作后，把插件生成的文件保存到你选择的位置。";
            case "system.logs": return "在你主动操作后，按插件声明的检索词读取近期系统日志中的匹配行。";
            case "clipboard": return "在你操作工具时读取或写入剪贴板内容。";
            case "notification": return "使用插件声明的通知类别显示或取消通知。";
            case "accessibility.manage": return "查看并修改设备上已安装无障碍服务的启用状态。";
            case "shizuku.control": return "请求本应用的 Shizuku 授权并连接受控系统服务。";
            default: return "插件请求使用此能力。";
        }
    }
}
