package com.androidtoolsuite.runtime.contract;

public enum RpcErrorCode {
    INVALID_REQUEST,
    PROTOCOL_MISMATCH,
    CAPABILITY_UNDECLARED,
    CAPABILITY_UNAVAILABLE,
    CAPABILITY_VERSION_MISMATCH,
    PERMISSION_DENIED,
    CONSENT_REQUIRED,
    PROVIDER_OFFLINE,
    TIMEOUT,
    CANCELLED,
    CANCEL_PENDING,
    RESOURCE_LIMIT,
    NOT_SUPPORTED,
    INTERNAL
}
